New changes

diff --git a/bin/mockdata b/bin/mockdata
--- a/bin/mockdata
+++ b/bin/mockdata
@@ -1,1 +1,41 @@
+#!/usr/bin/env bash
+
+echo "Starting InsightLake Mock Data Generator..."
+
+export JAVA_HOME=/usr/java/default
+
+if [ "$JAVA_HOME" != "" ]; then
+    #echo "run java in $JAVA_HOME"
+    JAVA_HOME=$JAVA_HOME
+fi
+
+if [ "$JAVA_HOME" = "" ]; then
+    echo "Error: JAVA_HOME is not set."
+    exit 1
+fi
+
+JAVA=$JAVA_HOME/bin/java
+JAVA_HEAP_MAX=-Xmx1000m
+
+PRG="${0}"
+
+while [ -h "${PRG}" ]; do
+  ls=`ls -ld "${PRG}"`
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '/.*' > /dev/null; then
+    PRG="$link"
+  else
+    PRG=`dirname "${PRG}"`/"$link"
+  fi
+done
+
+EDP_HOME=`dirname ${PRG}`
+EDP_HOME=`cd ${EDP_HOME}/..;pwd`
+
+CLASSPATH="$EDP_HOME/conf:$EDP_HOME/libs:$EDP_HOME/bin"
+
+for f in $EDP_HOME/libs/*.jar; do
+    CLASSPATH=${CLASSPATH}:$f;
+done
+
 java -jar ../libs/mockdata.jar $@
